---
title: "git_00"
author: "April Galvan"
date: "Year 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
I have a fairy by my side.  
Which says I must not sleep,  
When once in pain I loudly cried. 
It said "You must not weep".  
If, full of mirth, I smile and grin,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make 
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Everybody, everywhere seeks happiness, it’s true,  
But finding it and keeping it seem difficult to do.  
Difficult because we think that happiness is found   
Only in the places where wealth and fame abound.And so we go on searching in  palaces of pleasure   
Seeking recognition and monetary treasure,  
Unaware that happiness is just a state of mind  
Within the reach of everyone who takes time to be kind.  
For in making others happy we will be happy, too.  
For the happiness you give away returns to shine on you.  